# Generated by Django 4.2 on 2023-05-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
            preserve_default=False,
        ),
    ]
