# Generated by Django 4.2 on 2023-05-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_drinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzas',
            name='type',
        ),
    ]
