# Generated by Django 4.2 on 2023-05-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_type'),
        ('menu', '0002_drinks_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
    ]
