# Generated by Django 4.2 on 2023-05-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_pizzas_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
