# Generated by Django 4.2 on 2023-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_drinks_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
