# Generated by Django 4.2 on 2023-05-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_drink_price_alter_pizza_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='image',
        ),
        migrations.CreateModel(
            name='PizzaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.drink')),
            ],
        ),
    ]
