# Generated by Django 4.2 on 2023-05-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_name_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='http://127.0.0.1:8000/media/default.jpg', max_length=9999),
        ),
    ]
