# Generated by Django 4.2 on 2023-05-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='expDate',
        ),
    ]
