# Generated by Django 4.2 on 2023-05-11 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_payment_expmont_payment_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardHolder',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999, message='The Phone number cannot be longer than 7 characters'), django.core.validators.MinValueValidator(1000000000000000, message='The Phone number must be at least 7 characters long')]),
        ),
    ]
