# Generated by Django 4.2 on 2023-05-11 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_payment_cardholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardHolder',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardNr',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999, message='The Phone number cannot be longer than 7 characters'), django.core.validators.MinValueValidator(1000000, message='The Phone number must be at least 7 characters long')]),
        ),
    ]
