# Generated by Django 4.2 on 2023-05-11 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_payment_cardholder_alter_payment_cardnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardNr',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999, message='The Card number cannot be longer than 7 characters'), django.core.validators.MinValueValidator(1000000000000000, message='The Card number must be at least 7 characters long')]),
        ),
    ]
