# Generated by Django 4.2 on 2023-05-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_payment_cardnr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cardNr',
            new_name='cardNumber',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='ExpMont',
            new_name='expMonth',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='expDate',
            new_name='expYear',
        ),
    ]
