# Generated by Django 4.2 on 2023-05-12 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_cardnr_payment_cardnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardNumber',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999, message='The Card number cannot be longer than 16 characters'), django.core.validators.MinValueValidator(1000000000000000, message='The Card number must be at least 16 characters long')]),
        ),
    ]
