# Generated by Django 4.2 on 2023-05-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_payment_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardNumber',
            field=models.CharField(max_length=16),
        ),
    ]
