# Generated by Django 4.2 on 2023-05-12 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_payment_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999, message='The CVV number must be 3 digits.'), django.core.validators.MinValueValidator(100, message='The CVV number must be 3 digits.')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expMonth',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12, message='The expiring month must be a digit in the range of 1-12.'), django.core.validators.MinValueValidator(1, message='The expiring month must be a digit in the range of 1-12.')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expYear',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(33, message="The expiring year can't be more then 10 years from now."), django.core.validators.MinValueValidator(23, message='The expiring year must be in the future.')]),
        ),
    ]
