# Generated by Django 4.2 on 2023-05-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_payment_cvv_alter_payment_expmonth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cardHolder',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cardNumber',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expMonth',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expYear',
        ),
    ]
