# Generated by Django 4.2 on 2023-05-12 10:06

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_payment_cardholder_remove_payment_cardnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cardHolder',
            field=models.CharField(default='e', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='cardNumber',
            field=creditcards.models.CardNumberField(max_length=25, null=True, verbose_name='card number'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvvCode',
            field=creditcards.models.SecurityCodeField(max_length=4, null=True, verbose_name='security code'),
        ),
        migrations.AddField(
            model_name='payment',
            name='expDate',
            field=creditcards.models.CardExpiryField(null=True, verbose_name='expiration date'),
        ),
    ]
