# Generated by Django 4.2 on 2023-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_payment_cardholder_payment_cardnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardHolder',
            field=models.CharField(max_length=255, verbose_name='card holder'),
        ),
    ]
