# Generated by Django 4.2 on 2023-05-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='part_of_offer',
            field=models.BooleanField(default=False),
        ),
    ]
