# Generated by Django 4.2 on 2023-05-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzasinoffers',
            old_name='pizzaoffers',
            new_name='pizzaOffer',
        ),
    ]
