# Generated by Django 4.2 on 2023-05-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_offer_image_discount_image_pizzaoffer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.CharField(default='halló', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='bæbæ', max_length=255),
            preserve_default=False,
        ),
    ]
