# Generated by Django 4.2 on 2023-05-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('offers', '0004_discount_description_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaoffer',
            name='pizzas',
            field=models.ManyToManyField(blank=True, to='menu.pizza'),
        ),
    ]
