# Generated by Django 4.2 on 2023-05-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_pizzaoffer_pizzas'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=255)),
            ],
        ),
    ]
