# Generated by Django 4.2 on 2023-05-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offers.offtype'),
            preserve_default=False,
        ),
    ]
